server:
  port: 9095

spring:
  application:
    name: jpa2

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpaDB?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: jpa_user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # mysql? sql platform ??

logging:
  level:
    sql: debug